export const data = {
  products: [
    {
      id: "1",
      name: "Levi's T-Shirt",
      image: "/images/p1.jpg",
      price: 30,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality Tshirt",
    },
    {
      id: "2",
      name: "Nike T-Shirt",
      image: "/images/p2.png",
      price: 60,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "3",
      name: "Adidas T-Shirt",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      id: "4",
      name: "US Polo T-Shirt",
      image: "/images/p4.png",
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
